# fly.toml app configuration file generated for stremo-server on 2023-08-31T20:54:40-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "stremo-server"
primary_region = "ord"

# [build]

# [services]
# protocol = "tcp"
# internal_port = 5000
# force_https = true
# auto_stop_machines = true
# auto_start_machines = true
# min_machines_running = 0
# processes = ["app"]

[[services]]
internal_port = 5000
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20

[[services.ports]]
handlers = ["http"]
port = "80"

[[services.ports]]
handlers = ["tls", "http"]
port = "443"

[[services.tcp_checks]]
interval = 10000
timeout = 2000
